---

version: '2'

services:
  php-sj:
    build: ./docker/php
    container_name: "php-sj"
    volumes:
      - ./app:/var/www/html
    restart: "unless-stopped"
    depends_on:
      - postgres-sj
    networks:
      - sj-network

  nginx-sj:
    image: nginx:1.20
    container_name: "nginx-sj"
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www/html
      - ./docker/nginx/local.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-sj
    networks:
      - sj-network

  postgres-sj:
    image: postgres:13
    container_name: "postgres-sj"
    restart: unless-stopped
    ports:
      - '5432:5432'
    env_file:
      - ./app/.env
    volumes:
      - dbdata-sj:/var/lib/postgresql/data
    networks:
      - sj-network

networks:
  sj-network:
    driver: bridge

volumes:
  dbdata-sj:
    driver: local