courses:
    path: /student-courses/{studentId}
    controller: App\Controller\StudentCoursesController::getCourses

stydents-voen:
    path: /voen
    controller: App\Controller\StudentsController::getVoen
